### PR TITLE
response interceptor

### PR DESCRIPTION
**Pull request by sashrika**
Implemented Response Highlighter Interceptor

### CODE REVIEW

**Comment by sashrika** [comment]
@surangak @harsha89 I implemented the  Response Highlighter Interceptor :)
In the mailing list i've attached a screenshot.

Don't merge this, we have to figure out few things.

**Comment by surangak** [comment]
@sashrika , hmm... what exactly do we need to figure out to get this wrapped up? :-)

**Comment by sashrika** [comment]
@surangak  , the big class I copy pasted should actually comes from fhir. But it shows Exception Interceptor and Loggin interceptor but not this one. So I copy and pasted the code. We have to figure out why this class is not bundled in out hapi version. that is the only concern :)

**Comment by surangak** [comment]
Hmm.... @sashrika , I looked at the hapi github repo, and I see that class at https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseHighlighterInterceptor.java

How are you trying to import it? maybe you're looking in the wrong place? :-(

**Comment by surangak** [comment]
Heya,

@sashrika  @harsha89 , the problem is that this class isn't in HAPI FHIR 1.0, so we need to upgrade to 1.1.
Hmm.... I wonder if there's a willing young student who's keep to do the upgrade to HAPI FHIR 1.1 for us? ;)

**Comment by harsha89** [comment]
Oopz I didn't notice that. They have done a another release. Upgrade shouldn't be hard. :)

**Comment by surangak** [comment]
I upgraded to 1.1. You can now use import ca.uhn.fhir.rest.server.interceptor.ResponseHighlighterInterceptor;

@harsha89  @sashrika  :)

**Comment by sashrika** [comment]
@surangak @harsha89  Thank you very much (y) (Y) I'll do a pull request with the new changes

**Comment by surangak** [comment]
Killed for #96

**Pull request closed without merging**
