### PR TITLE
FM-247 Add Swagger SDK generation frontend implementation

### PR DESCRIPTION
**Pull request by eunice18**
JIRA Issue : https://issues.openmrs.org/browse/FM-247

### CODE REVIEW

**Comment by eunice18** [comment]
hello @harsha89 I'm currently working on improvements.

**Comment by harsha89** [comment]
@eunice18 please include a screenshot and complete this soon.

**Comment by eunice18** [comment]
image

**Comment by eunice18** [comment]
image

**Comment by eunice18** [comment]
@harsha89 I have added screenshots and completed this.

**Comment by kaweesi** [comment]
https://issues.openmrs.org/browse/FM-251

**Pull request merged**
