### PR TITLE
Add chained parameters to search for AllergyIntolerence by a patient name

### PR DESCRIPTION
**Pull request by vaibhav-hp**

### CODE REVIEW

**Comment by harsha89** [comment]
Looks good @vaibhav-hp . Shall we add a test case for api method too?

**Comment by vaibhav-hp** [comment]
Hi  suranga and harsha89

Please,review and let me know,If any more changes are required.

Thanks :-)

**Comment by vaibhav-hp** [comment]
Hi Harsha89,

Thanks for fast response :-)

Sure I'll write up a Junit test as well

**Comment by harsha89** [comment]
Great thanks @vaibhav-hp

**Comment by surangak** [comment]
Agreed. Thanks Vaibhav :)

**Comment by harsha89** [comment]
I'm merging the pull request. @vaibhav-hp please send a pull request with a test. :)

**Pull request merged**
