### PR TITLE
SYNCT-186: Added unit tests for FHIRClientHelper

### PR DESCRIPTION
**Pull request by areklalo**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@oskarhinc did you see this build failure? https://ci.openmrs.org/browse/FHIR-FM-161

**Comment by oskarhinc** [comment]
@dkayiwa The CI build passed on this pull request when it was pushed. Unfortunately, there was no info that the build fails, when the master branch was updated. I've seen it after I've merged it, and already fixed it in mine pull request, so the build passed now.

**Comment by dkayiwa** [comment]
@oskarhinc thanks for attending to it in a timely manner! 👍 
You can make a build a favourite in bamboo such that you automatically get notified whenever there is a failure.

**Comment by oskarhinc** [comment]
@dkayiwa Thanks, I didn't know it!

**Pull request merged**
