### PR TITLE
FM-207: Created Encounter strategy. Moved FHIR API logic for the encounter to default Encounter strategy.

### PR DESCRIPTION
**Pull request by pkornowski**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@pkornowski are you still working on this?

**Comment by pkornowski** [comment]
@dkayiwa 
Currently, we are focusing on MVP for Sync 2.0. For this, we would like to implement fully synchronizations logic for the Patient object. I will back to this strategy after that.

**Comment by dkayiwa** [comment]
@pkornowski so do will close this pr for now?

**Comment by pkornowski** [comment]
@dkayiwa 
Yes, if it is necessary.

**Comment by dkayiwa** [comment]
Ping me to reopen when you resume working on it.
We are just trying to clean up our pull request queue. 😊

**Pull request closed without merging**
