### PR TITLE
FM-266: Return 401 instead of 500 when user is unauthenticated

### PR DESCRIPTION
**Pull request by valvijo**
## Description of what I changed

I added a validation to send a 401 HTTP error code in case the user is not authenticated to access the resource.

## Issue I worked on

see https://issues.openmrs.org/browse/FM-266

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [X] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [X] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [X] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by corneliouzbett** [comment]
@valvijo can you fix the link the Jira issue worked on and also add some description of what you changed

> ## Description of what I changed
> ## Issue I worked on
> see https://issues.openmrs.org/browse/SYNCT-
> 
> ## Checklist: I completed these to help reviewers :)
> * [ ]  My pull request only contains **ONE single commit**
>   (the number above, next to the 'Commits' tab is 1).
>   No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one
> * [x]  My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
>   No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`
> * [ ]  I have **added tests** to cover my changes. (If you refactored
>   existing code that was well tested you do not have to add tests)
>   No? -> write tests and add them to this commit `git add . && git commit --amend`
> * [x]  I ran `mvn clean package` right before creating this pull request and
>   added all formatting changes to my commit.
>   No? -> execute above command
> * [ ]  All new and existing **tests passed**.
>   No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.
> * [x]  My pull request is **based on the latest changes** of the master branch.
>   No? Unsure? -> execute command `git pull --rebase upstream master`

**Comment by corneliouzbett** [comment]
Also, squash your commits to **ONE single commit**

**Comment by valvijo** [comment]
Done @corneliouzbett. Please validate

**Comment by dkayiwa** [comment]
@valvijo can you take a look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by joeldenning** [comment]
The single commit rule is one I don't think needs to exist, since we can do [Github Squash and Merge](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) which automatically turns all PRs into one commit anyway. This repository only has squash and merge commits enabled, which means that there is no possible way that a PR will result in more than one commit on master branch.

@valvijo this PR seems to handle the case where the `Authorization` http header is missing entirely, but it doesn't seem to handle when the Authorization header is sent but has an invalid session/auth token. Have you confirmed that when you let your session expire with time that requests to the FHIR module still result in a 401 instead of a 500?

**Comment by valvijo** [comment]
@joeldenning the Authorization header with an invalid session is working fine. I only added a line to exit the method after the error is sent. Note that in this particular case a `SC_FORBIDDEN` is being sent.

Maybe the description of the JIRA ticket should be updated to explain the full extent of the issue.

**Comment by dkayiwa** [comment]
@valvijo can you claim the ticket and take it through the JIRA workflow as detailed at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Pull request merged**
