### PR TITLE
look for encounter in context and choose appropriate create method

### PR DESCRIPTION
**Pull request by djfunksalot**
please see talk topic:
https://talk.openmrs.org/t/setting-encounter-id-in-fhir-observation/18874

### CODE REVIEW

**Comment by dkayiwa** [comment]
Thanks @djfunksalot for the contribution. Do you mind creating a ticket for this? https://wiki.openmrs.org/display/docs/Tickets

**Comment by djfunksalot** [comment]
sure @dkayiwa.  looks like i need to create an account.  I'll put in the request once that's ready

**Comment by dkayiwa** [comment]
Did you request for the necessary permission?

**Comment by djfunksalot** [comment]
Yes, I just created it:
https://issues.openmrs.org/browse/FM-248
hope I did it right!

**Comment by dkayiwa** [comment]
Did you also got a chance to look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
Can you also create some tests for this change?

**Comment by djfunksalot** [comment]
I just read the Pull Request Tips and will be sure follow these conventions.
I can create a test, should I put it in tests in ObsServiceTest.java?

**Comment by dkayiwa** [comment]
Yes put it in there.

**Comment by dkayiwa** [comment]
@djfunksalot how is this going?

**Comment by djfunksalot** [comment]
It’s ok.   I’m sorry for the delay I will put my changes in there.    
Thanks,
Steve

**Comment by dkayiwa** [comment]
@djfunksalot do not hesitate to ask us if you need help 😊

**Comment by djfunksalot** [comment]
thanks @dkayiwa!  I just added a test

**Comment by dkayiwa** [comment]
@djfunksalot do you think you can squash these commits into one which has the ticket number in the commit message as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
@djfunksalot you will also need to take the JIRA ticket through the process specified at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
@djfunksalot are you still working on this?

**Comment by djfunksalot** [comment]
Yes.   Still working on it!  Thank you

**Comment by djfunksalot** [comment]
replacing with a new pull request

**Pull request closed without merging**
