### PR TITLE
FM-64 Support export of OpenMRS data using FHIR Condition Resource.

### PR DESCRIPTION
**Pull request by TheeeX**
Sub-Task : FM-65 : Add features for users to search for and retrieve one or many Condition resources: searchConditionsByPatient() implemented
mvn clean package build passing

### CODE REVIEW

**Comment by TheeeX** [comment]
@harsha89 please review.

**Comment by harsha89** [comment]
Can we add a test case?

**Comment by TheeeX** [comment]
Test case for **searchConditionsByPatient()** requires a dataset which has _patient and condition resource_. I found one at [openmrs-module-emrapi](https://github.com/openmrs/openmrs-module-emrapi) - conditionListDataSet.xml (https://github.com/openmrs/openmrs-module-emrapi/blob/master/condition-list/src/test/resources/conditionListDataSet.xml).
I copied conditionListDataSet.xml to fhir module test/resources folder, on exporting it throws an exception:

> org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK_4PIDXMF32TQRMFERVDL0MGJ9C: PUBLIC.PATIENT_IDENTIFIER FOREIGN KEY(IDENTIFIER_TYPE) REFERENCES PUBLIC.PATIENT_IDENTIFIER_TYPE(PATIENT_IDENTIFIER_TYPE_ID) (3)"; SQL statement:
> update PATIENT_IDENTIFIER set DATE_CREATED = ?, PATIENT_ID = ?, IDENTIFIER = ?, IDENTIFIER_TYPE = ?, CREATOR = ?, UUID = ?, PREFERRED = ?, VOIDED = ? where PATIENT_IDENTIFIER_ID = ? [23506-187]

Is there a way to use orignal conditionListDataSet.xml from openmrs-module-emrapi module?

**Comment by dkayiwa** [comment]
@TheeeX why not just use an existing patient identifier type?

**Comment by dkayiwa** [comment]
@TheeeX did you see my question above?

**Comment by dkayiwa** [comment]
@TheeeX i can reopen if you resume working on this.

**Pull request closed without merging**
