### PR TITLE
FM-207: Create FHIR Strategy for Encounter object

### PR DESCRIPTION
**Pull request by pmuchowski**

### CODE REVIEW

**Comment by awalkowiak** [comment]
@dkayiwa is it possible for me and @pmuchowski to get write access in this module? Or there is other merging process in this module?

**Comment by dkayiwa** [comment]
@awalkowiak you should by now have a write access invitation

**Comment by pmuchowski** [comment]
@dkayiwa can you give me write access too, I will need it later

**Comment by dkayiwa** [comment]
@pmuchowski invitation sent

**Comment by awalkowiak** [comment]
@dkayiwa got it thanks

**Pull request merged**
